# Generated by Django 4.2.5 on 2023-12-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_remove_courses_students_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
